      subroutine VTSETUP()

c***********************************************************************
c     
c     Setup the VAMPIRtrace instrumentation
c     copyright - daresbury laboratory 1992
c     author    - w. smith         may 1992
c     
c     wl
c     2003/05/08 08:45:09
c     1.4
c     Exp
c     
c***********************************************************************

      integer ierr
#include "VT.inc"

      call VTSYMDEF( 1, 'parset', 'Setup', ierr)
      call VTSYMDEF( 2, 'sysdef', 'Setup', ierr)
      call VTSYMDEF( 3, 'simdef', 'Setup', ierr)
      call VTSYMDEF( 4, 'sysgen', 'Setup', ierr)
      call VTSYMDEF( 5, 'sysbook', 'Setup', ierr)
      call VTSYMDEF( 6, 'systemp', 'Setup', ierr)
      call VTSYMDEF( 7, 'sysinit', 'Setup', ierr)
      call VTSYMDEF( 8, 'vertest', 'Integration', ierr)
      call VTSYMDEF( 9, 'parlst_nsq', 'NeighList', ierr)
      call VTSYMDEF(10, 'parlink', 'NeighList', ierr)
      call VTSYMDEF(11, 'parlst', 'NeighList', ierr)
      call VTSYMDEF(12, 'parneulst', 'NeighList', ierr)
      call VTSYMDEF(13, 'parlinkneu', 'NeighList', ierr)
      call VTSYMDEF(14, 'multiple_nsq', 'Forces', ierr)
      call VTSYMDEF(15, 'forces', 'Forces', ierr)
      call VTSYMDEF(16, 'multiple', 'Forces', ierr)
      call VTSYMDEF(17, 'forcesneu', 'Forces', ierr)
      call VTSYMDEF(18, 'multipleneu', 'Forces', ierr)
      call VTSYMDEF(19, 'thbfrc', 'Forces', ierr)
      call VTSYMDEF(20, 'fbpfrc', 'Forces', ierr)
      call VTSYMDEF(21, 'bndfrc', 'Forces', ierr)
      call VTSYMDEF(22, 'angfrc', 'Forces', ierr)
      call VTSYMDEF(23, 'dihfrc', 'Forces', ierr)
      call VTSYMDEF(24, 'invfrc', 'Forces', ierr)
      call VTSYMDEF(25, 'tethfrc', 'Forces', ierr)
      call VTSYMDEF(26, 'shlfrc', 'Forces', ierr)
      call VTSYMDEF(27, 'extnfld', 'Forces', ierr)
      call VTSYMDEF(28, 'gsums', 'LoopComm', ierr) 
      call VTSYMDEF(29, 'fcap', 'Integration', ierr) 
      call VTSYMDEF(30, 'strucopt', 'Integration', ierr) 
      call VTSYMDEF(31, 'freeze', 'Integration', ierr) 
      call VTSYMDEF(32, 'nve_0', 'Integration', ierr) 
      call VTSYMDEF(33, 'nve_1', 'Integration', ierr) 
      call VTSYMDEF(34, 'npt_b1', 'Integration', ierr) 
      call VTSYMDEF(35, 'nst_b1', 'Integration', ierr) 
      call VTSYMDEF(36, 'npt_h1', 'Integration', ierr) 
      call VTSYMDEF(37, 'nst_h1', 'Integration', ierr) 
      call VTSYMDEF(38, 'nptq_b1', 'Integration', ierr) 
      call VTSYMDEF(39, 'nptq_b2', 'Integration', ierr) 
      call VTSYMDEF(40, 'nstq_b1', 'Integration', ierr) 
      call VTSYMDEF(41, 'nstq_b2', 'Integration', ierr) 
      call VTSYMDEF(42, 'nptq_h1', 'Integration', ierr) 
      call VTSYMDEF(43, 'nptq_h2', 'Integration', ierr) 
      call VTSYMDEF(44, 'nstq_h1', 'Integration', ierr) 
      call VTSYMDEF(45, 'nstq_h1', 'Integration', ierr) 
      call VTSYMDEF(46, 'nveq_1', 'Integration', ierr) 
      call VTSYMDEF(47, 'nveq_2', 'Integration', ierr) 
      call VTSYMDEF(48, 'nvt_b0', 'Integration', ierr) 
      call VTSYMDEF(49, 'nvt_b1', 'Integration', ierr) 
      call VTSYMDEF(50, 'nvt_e0', 'Integration', ierr) 
      call VTSYMDEF(51, 'nvt_e1', 'Integration', ierr) 
      call VTSYMDEF(52, 'nvt_h0', 'Integration', ierr) 
      call VTSYMDEF(53, 'nvt_h1', 'Integration', ierr) 
      call VTSYMDEF(54, 'nvtq_b1', 'Integration', ierr) 
      call VTSYMDEF(55, 'nvtq_b2', 'Integration', ierr) 
      call VTSYMDEF(56, 'nvtq_h1', 'Integration', ierr) 
      call VTSYMDEF(57, 'nvtq_h2', 'Integration', ierr) 
      call VTSYMDEF(58, 'pmf_1', 'Integration', ierr) 
      call VTSYMDEF(59, 'quatqnch', 'Integration', ierr) 
      call VTSYMDEF(60, 'quench', 'Integration', ierr) 
      call VTSYMDEF(61, 'corshl', 'Integration', ierr) 
      call VTSYMDEF(62, 'shlqnch', 'Integration', ierr) 
      call VTSYMDEF(63, 'vscale', 'Integration', ierr) 
      call VTSYMDEF(64, 'vscaleg', 'Integration', ierr) 
      call VTSYMDEF(65, 'xscale', 'Integration', ierr) 
      call VTSYMDEF(66, 'static', 'Properties', ierr) 
      call VTSYMDEF(67, 'zden0', 'Properties', ierr) 
      call VTSYMDEF(68, 'output', 'Output', ierr) 
      call VTSYMDEF(69, 'result', 'Output', ierr) 
      call VTSYMDEF(70, 'traject', 'Output', ierr) 
      call VTSYMDEF(71, 'revive', 'Output', ierr) 
      call VTSYMDEF(72, 'rdf0', 'Properties', ierr) 
      call VTSYMDEF(73, 'vertest1', 'Integration', ierr)
      call VTSYMDEF(74, 'diffsn0', 'Properties', ierr)
      call VTSYMDEF(75, 'rdf0neu', 'Properties', ierr) 
      call VTSYMDEF(76, 'rdf0_sw', 'Properties', ierr) 
      call VTSYMDEF(77, 'exclude', 'Setup', ierr) 
      call VTSYMDEF(78, 'exclude_atom', 'Setup', ierr) 
      call VTSYMDEF(79, 'exclude_link', 'Setup', ierr) 
      call VTSYMDEF(80, 'excludeneu', 'Setup', ierr) 
      call VTSYMDEF(81, 'images', 'Forces', ierr) 
      call VTSYMDEF(82, 'primlst', 'NeighList', ierr) 
      call VTSYMDEF(83, 'srfrce', 'Forces', ierr) 
      call VTSYMDEF(84, 'coul0', 'Forces', ierr) 
      call VTSYMDEF(85, 'coul1', 'Forces', ierr) 
      call VTSYMDEF(86, 'coul2', 'Forces', ierr) 
      call VTSYMDEF(87, 'coul3', 'Forces', ierr) 
      call VTSYMDEF(88, 'coul4', 'Forces', ierr) 
      call VTSYMDEF(89, 'dihfrc_rsq', 'Forces', ierr) 
      call VTSYMDEF(90, 'dihfrc_4pt', 'Forces', ierr) 
      call VTSYMDEF(91, 'coul0neu', 'Forces', ierr) 
      call VTSYMDEF(92, 'coul2neu', 'Forces', ierr) 
      call VTSYMDEF(93, 'coul3neu', 'Forces', ierr) 
      call VTSYMDEF(94, 'coul0_sw', 'Forces', ierr) 
      call VTSYMDEF(95, 'coul2_sw', 'Forces', ierr) 
      call VTSYMDEF(96, 'coul3_sw', 'Forces', ierr) 
      call VTSYMDEF(97, 'ewald1', 'Forces', ierr) 
      call VTSYMDEF(98, 'ewald1a', 'Forces', ierr) 
      call VTSYMDEF(99, 'main', 'Simulation', ierr)
      call VTSYMDEF(100, 'ewald2', 'Forces', ierr) 
      call VTSYMDEF(101, 'ewald2_rsq', 'Forces', ierr) 
      call VTSYMDEF(102, 'ewald2_4pt', 'Forces', ierr) 
      call VTSYMDEF(103, 'ewald3', 'Forces', ierr) 
      call VTSYMDEF(104, 'ewald3_neu', 'Forces', ierr) 
      call VTSYMDEF(105, 'ewald4', 'Forces', ierr) 
      call VTSYMDEF(106, 'ewald4_rsq', 'Forces', ierr) 
      call VTSYMDEF(107, 'ewald4_4pt', 'Forces', ierr) 
      call VTSYMDEF(108, 'ewcorr', 'Forces', ierr) 
      call VTSYMDEF(109, 'ewcorr_neu', 'Forces', ierr) 
      call VTSYMDEF(110, 'scdens', 'Forces', ierr) 
      call VTSYMDEF(111, 'denloc', 'Forces', ierr) 
      call VTSYMDEF(112, 'suttchen', 'Forces', ierr) 
      call VTSYMDEF(113, 'neutlst', 'NeighList', ierr) 
      call VTSYMDEF(114, 'srfrce_4pt', 'Forces', ierr) 
      call VTSYMDEF(115, 'srfrceneu', 'Forces', ierr) 
      call VTSYMDEF(116, 'srfrceneu_rsq', 'Forces', ierr) 
      call VTSYMDEF(117, 'srfrceneu_4pt', 'Forces', ierr) 
      call VTSYMDEF(118, 'prneulst', 'NeighList', ierr) 
      call VTSYMDEF(119, 'merge', 'Integration', ierr) 
      call VTSYMDEF(120, 'merge1', 'Integration', ierr) 
      call VTSYMDEF(121, 'merge1_hcube', 'Integration', ierr) 
      call VTSYMDEF(122, 'merge4', 'Integration', ierr) 
      call VTSYMDEF(123, 'merge_hcube', 'Integration', ierr) 
      call VTSYMDEF(124, 'shlmerge', 'Integration', ierr) 
      call VTSYMDEF(125, 'shmove', 'Integration', ierr) 
      call VTSYMDEF(126, 'rdshake_1', 'Integration', ierr) 
      call VTSYMDEF(127, 'splice', 'Integration', ierr) 
      call VTSYMDEF(128, 'qshake', 'Integration', ierr) 
      call VTSYMDEF(129, 'bspcoe','Forces', ierr)
      call VTSYMDEF(130, 'bspgen','Forces', ierr)
      call VTSYMDEF(131, 'cfgscan','Setup', ierr)
      call VTSYMDEF(132, 'conscan','Setup', ierr)
      call VTSYMDEF(133, 'diffsn1','Properties', ierr)
      call VTSYMDEF(134, 'duni','Setup', ierr)
      call VTSYMDEF(135, 'erfcgen','Setup', ierr)
      call VTSYMDEF(136, 'erfcgen_rsq','Setup', ierr)
      call VTSYMDEF(137, 'ewald2neu','Forces', ierr)
      call VTSYMDEF(138, 'ewald_spme','Forces', ierr)
      call VTSYMDEF(139, 'fldscan','Setup', ierr)
      call VTSYMDEF(140, 'forgen','Setup', ierr)
      call VTSYMDEF(141, 'forgen_rsq','Setup', ierr)
      call VTSYMDEF(142, 'fortab','Setup', ierr)
      call VTSYMDEF(143, 'fortab_rsq','Setup', ierr)
      call VTSYMDEF(144, 'gauss','Setup', ierr)
      call VTSYMDEF(145, 'intlist','Setup', ierr)
      call VTSYMDEF(146, 'kinstr','Properties', ierr)
      call VTSYMDEF(147, 'lrcmetal','Properties', ierr)
      call VTSYMDEF(148, 'lrcorrect','Properties', ierr)
      call VTSYMDEF(149, 'merge.systol','Integration', ierr)
      call VTSYMDEF(150, 'merge1.systol','Integration', ierr)
      call VTSYMDEF(151, 'metgen','Setup', ierr)
      call VTSYMDEF(152, 'metgen_rsq','Setup', ierr)
      call VTSYMDEF(153, 'passcon','Setup', ierr)
      call VTSYMDEF(154, 'passpmf','Setup', ierr)
      call VTSYMDEF(155, 'passquat','Setup', ierr)
      call VTSYMDEF(156, 'pmf_shake','Integration', ierr)
      call VTSYMDEF(157, 'quatbook','Setup', ierr)
      call VTSYMDEF(158, 'spl_cexp','Forces', ierr)
      call VTSYMDEF(159, 'spme_for','Forces', ierr)
      call VTSYMDEF(160, 'srfrce_rsq','Forces', ierr)
      call VTSYMDEF(161, 'suttchen_4pt','Forces', ierr)
      call VTSYMDEF(162, 'suttchen_rsq','Forces', ierr)
      call VTSYMDEF(163, 'traject_u','Output', ierr)
      call VTSYMDEF(164, 'merge4.hcube','Integration', ierr)
      call VTSYMDEF(165, 'npt_b0','Integration', ierr)
      call VTSYMDEF(166, 'nst_b0','Integration', ierr)
      call VTSYMDEF(167, 'nst_h0','Integration', ierr)
      call VTSYMDEF(168, 'zden1','Properties', ierr)
      call VTSYMDEF(169, 'rdf1','Properties', ierr)
      call VTSYMDEF(170, 'hkgen','Setup', ierr)
      call VTSYMDEF(171, 'hkewald1','Forces', ierr)
      call VTSYMDEF(172, 'hkewald2','Forces', ierr)
      call VTSYMDEF(173, 'hkewald3','Forces', ierr)

      end
